version: "3.7"

networks:
    AIservice:
        external: true


services:
  backend:
    build: FastAPI_backend
    ports:
      - 8111:8000
    networks:       
      AIservice: 
        aliases: 
          - backend.docker
    volumes:
      - ./FastAPI_backend:/app
      - ./src:/src
  frontend:
    build: streamlit_app
    ports:
      - 8501:8080
    networks: 
      AIservice:
        aliases: 
          - frontend.docker
    depends_on:
      - backend
    volumes:
       - ./streamlit_app:/app
       - ./src:/src

  tensorboard:
    build:
      context: 'tensorboard_backend'
      dockerfile: "./Dockerfile"
    networks:       
      AIservice: 
        aliases: 
          - tensorboard.docker
    volumes:
      - ./src/models/text/text_neural_simple/layers:/app/text/text_neural_simple/layers
    ports:
    - 6109:6009
