version: "3"

services:

  tensorboard:
    container_name: ds_tensorboard
    #image: tensorflow/tensorflow:latest
    #command: tensorboard --logdir /app/models --host 127.0.0.1 --port 6009
    build:
      context: 'src/models'
      dockerfile: "./Dockerfile"
    network_mode: host
    ports:
    - "6009:6009"

  fastapi:
    container_name: ds_fastapi
    build: src/.
    command: "uvicorn fast:app --host 127.0.0.1 --port 8008 --reload"
    network_mode: host
    ports:
      - "8008:8008"
    # volumes:
    # - shared_volume:/app/models

  streamlit:
    container_name: ds_streamlit
    build: streamlit_app/.
    command: "streamlit run --server.port 8080 --server.enableCORS false app.py"
    ports:
      - "8080:8080"
    network_mode: host
    depends_on : 
    - fastapi
    # volumes:
    # - shared_volume:/app/models

# volumes:
#   shared_volume:

networks:
  host:
    name: host
    external: true